### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by roy-bankesh** [xiph/rnnoise#108]
Hi,
I am using a Ubuntu 14.04 PC to compile the project.

I am getting the following error after executing "./autogen.sh":

Updating build configuration files for rnnoise, please wait....
configure.ac:8: installing 'scripts/compile'
configure.ac:13: installing 'scripts/install-sh'
configure.ac:13: installing 'scripts/missing'
Makefile.am:9: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:9:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:9:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:9:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:9:   its definition is in aclocal's search path.
Makefile.am: installing 'scripts/depcomp'
autoreconf: automake failed with exit status: 1

**Comment by zaptrem** [comment]
How did you solve the seg fault?

**Comment by roy-bankesh** [comment]
@zaptrem In which stage you are getting the segmentation fault? Please elaborate the issue.

**Comment by Approximetal** [comment]
> @zaptrem In which stage you are getting the segmentation fault? Please elaborate the issue.
I solve this issue by install `libtool`
```
sudo apt-get install autoconf
sudo apt-get install libtool
```
