### ISSUE TITLE
Reference Research paper for this project ?

### ISSUE THREAD

**Issue by nitanshnagpal1** [xiph/rnnoise#157]

**Comment by jmvalin** [comment]
See this paper:

J.-M. Valin, A Hybrid DSP/Deep Learning Approach to Real-Time Full-Band Speech Enhancement, Proceedings of IEEE Multimedia Signal Processing (MMSP) Workshop, arXiv:1709.08243, 2018.
https://jmvalin.ca/papers/rnnoise_mmsp2018.pdf
