### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by TochiEbere** [xiph/rnnoise#163]
I tried to run the autogen.sh script but got the following error instead

Updating build configuration files for rnnoise, please wait....
Makefile.am:9: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:9:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:9:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:9:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:9:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

Pls how do I go about this?

**Comment by petterreinholdtsen** [comment]
[Tochi Ebere]
> I tried to run the autogen.sh script but got the following error instead
>
> Updating build configuration files for rnnoise, please wait....
> Makefile.am:9: error: Libtool library used but 'LIBTOOL' is undefined

Perhaps you system lack libtool?  On debian the package is called
'libtool'.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by TochiEbere** [comment]
Many thanks @petterreinholdtsen 

I tried installing the libtool just as you suggested and the rnnoise installed just fine.
