### ISSUE TITLE
Why the testing code only use half of the size of gru bias

### ISSUE THREAD

**Issue by benlin1996** [xiph/rnnoise#177]
Thanks for your wonderful code. When I train my own RNNoise model, I found that three gru bias sizes are twice as large as the origin RNNoise in rnn_data.c. But I print out the model in python and sure that my gru bias size is correct.

However, I read the compute_gru function in rnn.c and found that test code only use half of the gru bias in the testing, Can anyone explain why this case happen? And why the origin RNNoise model only keep half of the actual size of gru bias.

Thanks

**Comment by redasamik** [comment]
في ثلاثاء، 27 نيسان، 2021 في 11:43 ص، كتب benlin1996 <
***@***.***>:

**Comment by xfl218** [comment]
> Thanks for your wonderful code. When I train my own RNNoise model, I found that three gru bias sizes are twice as large as the origin RNNoise in rnn_data.c. But I print out the model in python and sure that my gru bias size is correct.
> 
> However, I read the compute_gru function in rnn.c and found that test code only use half of the gru bias in the testing, Can anyone explain why this case happen? And why the origin RNNoise model only keep half of the actual size of gru bias.
> 
> Thanks

@benlin1996 have you figured out the reason?
