### ISSUE TITLE
RNNoise not doing anything, result is identical to original

### ISSUE THREAD

**Issue by CaptainHorse** [xiph/rnnoise#184]
I'm using RNNoise yoinked from OBS-Studio repo as that works on Windows. RNNoise works on OBS-Studio really well, but when I try to use it in my own program it has no effect at all, I tried having my tower fan blow right towards the mic as I speak and play random noises from phone.

Captured audio format is mono 32-bit float, 480 size frames. Code snippet below:

```
auto st = rnnoise_create(nullptr);

int stopCap = 0;
std::vector<float> resRNN, resNone;
while (stopCap == 0) {
	std::vector<float> tmp;
	auto samples = captureAudio(&tmp);
	if (samples > 0) {
		for (const auto& t : tmp) resNone.emplace_back(t);
		rnnoise_process_frame(st, tmp.data(), tmp.data());
		for (const auto& t : tmp) resRNN.emplace_back(t);
	}
	stopCap = kbhit();
}
```

I output the data to PCM files and imported them into Audacity, comparing them show that they are the same.

![kuva](https://user-images.githubusercontent.com/14197772/118542086-355b1280-b75b-11eb-9e2b-6e8048d453d8.png)

**Comment by elaith9** [comment]
Did you solve this problem?

**Comment by CaptainHorse** [comment]
> Did you solve this problem?

Nope, didn't manage to find a way to get it to work unfortunately.

**Comment by ouyangkk** [comment]
I also met the same problem. Have you solved it yet?

**Comment by avalanche-tm** [comment]
Unfortunately no

> I also met the same problem. Have you solved it yet?

**Comment by Zadagu** [comment]
rnnoise has got a quite odd value range. It expects the float sample to be in the range of signed 16bit.
If your samples are between -1 and 1 rnnoise just sees silence and keeps all gains open, which results the output to be equal to the input.

**Comment by CaptainHorse** [comment]
> rnnoise has got a quite odd value range. It expects the float sample to be in the range of signed 16bit. If your samples are between -1 and 1 rnnoise just sees silence and keeps all gains open, which results the output to be equal to the input.

Well that explains some things.. remapping float ranges is bit ugly but it seems to work. (Upper is voice with background noise, lower is after running it through rnnoise).
![Picture](https://user-images.githubusercontent.com/14197772/150661445-af2d69a4-e02c-4eb3-8ae4-0eed6b784c47.png)
