### ISSUE TITLE
.so library

### ISSUE THREAD

**Issue by zhly0** [xiph/rnnoise#20]
Hi,thanks for your nice work,is it possible to provide a so library with a .h file?in the code,the run file is a sh file

**Comment by jmvalin** [comment]
We don't provide binaries, but the source code is all C90, so it should be easy to build with pretty much any compiler.

**Comment by zhly0** [comment]
Thanks for quik reply，I compile the code，and runs well，but there is a little questions：
1 the FRAME_SIZE is fixed to 480，and the result would be bad if I change the FRAME_SIZE.
2 the length is a little shorter than the input audio.
3 my input audio sample rate is 16k，after the denoise，the audio lost all the information in frequency area 6.7k - 8k hz.
expecting your reply.Thanks

**Comment by jmvalin** [comment]
1) Don't change the frame size (unless you want to update a lot of code and retrain a model)
2) Audio is processed in chunks, so maybe you don't have a multiple of the frame size. Also, the output will be delayed 10 ms
3) The input has to be 48 kHz (so the output is filtered at 20 kHz) for rnnoise to work well. 16 kHz will be suboptimal.

**Comment by zhly0** [comment]
Thanks,get it!

**Comment by ajithprinc** [comment]
> Thanks,get it!

Can you please tell me how you compile it..?
