### ISSUE TITLE
Training with already Clean and Noisy Data

### ISSUE THREAD

**Issue by rosotron** [xiph/rnnoise#233]
I already have noisy data that has been mixed with the clean data. I can't separate it. Is there any way to directly train the model with clean and noisy data?

**Comment by sanjuktasr** [comment]
The model will need the clean data along with the noise data to get trained as far as my understanding goes.

**Comment by jmvalin** [comment]
You need clean speech and noise for training. The training will then mix the speech and the noise, which is the only way to get an exact match between the clean and noisy speech.
