### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by sweetTT** [xiph/rnnoise#48]
“A Hybrid DSP/Deep Learning Approach to Real-Time Full-Band Speech Enhancement”
I want ask which magazine is this paper published in?I cant find answer on the Internet.

**Comment by jmvalin** [comment]
J.-M. Valin, A Hybrid DSP/Deep Learning Approach to Real-Time Full-Band Speech Enhancement, Proceedings of IEEE Multimedia Signal Processing (MMSP) Workshop, arXiv:1709.08243, 2018.

**Comment by sweetTT** [comment]
Thanks!
