### ISSUE TITLE
Ported to C++, visual studio 2017. Can't get the lib working

### ISSUE THREAD

**Issue by hsdxpro** [xiph/rnnoise#61]
I ported the code to C++ (not much change, just some allocation changes)

The library returns me 0 values, but I feed correct PCM data into it, any suggestion? (I didn't use make) I just copied the files over. Can somebody provide a working example in C or C++ (visual studio 2017) please?

**Comment by jagger2048** [comment]
Hi, 
The library returns 0 values maybe is that you feed the incorrect PCM data. 

In my test, when I fed the ***rnnoise_process_frame()*** function with S16 format PCM data, it works well. Instead, when I input F32 format PCM data, the function will return nearly 0 flags and don't denoise the data. The parameters of the function are a bit misleading.

I recently update the vs2017 project, you can reference it. 

https://github.com/jagger2048/rnnoise-windows

ps:  s16: 2 bytes integer, e.g. int16_t  ； f32, 4 bytes float, e.g. float, 0~1.

**Comment by hsdxpro** [comment]
Hi @jagger2048  I tried with signed 16 bit pure PCM data, after some investigation I was able to get some on 0 results, but it was very noisy (probably my mistake still). Let me check the windows version and thank you :)
