### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by mayurakewarv2** [xiph/rnnoise#90]
./autogen.sh: 10: ./autogen.sh: autoreconf: not found

**Comment by dm8tbr** [comment]
you are missing `autoconf`.
In general you should probably install the equivalent of `build-essential` for you distribution. That's like compiling things 101.

**Comment by mayurakewarv2** [comment]
> you are missing `autoconf`.
> In general you should probably install the equivalent of `build-essential` for you distribution. That's like compiling things 101.

Thanks

**Comment by csetanmayjain** [comment]
Hello, 
I use the following commands for Ubbuntu, and it works:

sudo apt-get install autoconf
sudo apt-get update && sudo apt-get install build-essential

You also need to install libtool, if not installed.

sudo apt-get install libtool
